/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  AttributionRegistry,
  AttributionRegistryInterface,
} from "../../contracts/AttributionRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ReasonHashStored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "reasonHashes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
    ],
    name: "storeReason",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
    ],
    name: "verifyReason",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102ec806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80634ec33a731461004657806374c4bef414610076578063bbd1a82f14610092575b600080fd5b610060600480360381019061005b91906101d8565b6100c2565b60405161006d919061021e565b60405180910390f35b610090600480360381019061008b91906101d8565b6100da565b005b6100ac60048036038101906100a791906101d8565b610181565b6040516100b9919061021e565b60405180910390f35b60006020528060005260406000206000915090505481565b6000806000838152602001908152602001600020541461012f576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161012690610296565b60405180910390fd5b4260008083815260200190815260200160002081905550807fc40b338033c9d4dc17c9ff6fdf89c816488886b733b77a2d5cfb138426c0fe1f42604051610176919061021e565b60405180910390a250565b6000806000838152602001908152602001600020549050919050565b600080fd5b6000819050919050565b6101b5816101a2565b81146101c057600080fd5b50565b6000813590506101d2816101ac565b92915050565b6000602082840312156101ee576101ed61019d565b5b60006101fc848285016101c3565b91505092915050565b6000819050919050565b61021881610205565b82525050565b6000602082019050610233600083018461020f565b92915050565b600082825260208201905092915050565b7f4861736820616c72656164792065786973747300000000000000000000000000600082015250565b6000610280601383610239565b915061028b8261024a565b602082019050919050565b600060208201905081810360008301526102af81610273565b905091905056fea2646970667358221220377e2d47dcdcee18450998d0dcb244d188b8d69d10e276210a21f9f3a73184ac64736f6c63430008180033";

type AttributionRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AttributionRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AttributionRegistry__factory extends ContractFactory {
  constructor(...args: AttributionRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AttributionRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AttributionRegistry__factory {
    return super.connect(runner) as AttributionRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AttributionRegistryInterface {
    return new Interface(_abi) as AttributionRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AttributionRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AttributionRegistry;
  }
}
