/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AttributionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "reasonHashes" | "storeReason" | "verifyReason"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReasonHashStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "reasonHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeReason",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReason",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "reasonHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReason",
    data: BytesLike
  ): Result;
}

export namespace ReasonHashStoredEvent {
  export type InputTuple = [hash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [hash: string, timestamp: bigint];
  export interface OutputObject {
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttributionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttributionRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttributionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reasonHashes: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  storeReason: TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;

  verifyReason: TypedContractMethod<[_hash: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reasonHashes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "storeReason"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyReason"
  ): TypedContractMethod<[_hash: BytesLike], [bigint], "view">;

  getEvent(
    key: "ReasonHashStored"
  ): TypedContractEvent<
    ReasonHashStoredEvent.InputTuple,
    ReasonHashStoredEvent.OutputTuple,
    ReasonHashStoredEvent.OutputObject
  >;

  filters: {
    "ReasonHashStored(bytes32,uint256)": TypedContractEvent<
      ReasonHashStoredEvent.InputTuple,
      ReasonHashStoredEvent.OutputTuple,
      ReasonHashStoredEvent.OutputObject
    >;
    ReasonHashStored: TypedContractEvent<
      ReasonHashStoredEvent.InputTuple,
      ReasonHashStoredEvent.OutputTuple,
      ReasonHashStoredEvent.OutputObject
    >;
  };
}
