/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttributionRegistry {
  export type TraceEntryStruct = {
    recorder: AddressLike;
    timestamp: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type TraceEntryStructOutput = [
    recorder: string,
    timestamp: bigint,
    blockNumber: bigint
  ] & { recorder: string; timestamp: bigint; blockNumber: bigint };
}

export interface AttributionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agent"
      | "getTrace"
      | "owner"
      | "setAgent"
      | "storeReason"
      | "traceCount"
      | "traceLog"
      | "traces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentUpdated" | "ReasonStored"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agent", values?: undefined): string;
  encodeFunctionData(functionFragment: "getTrace", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeReason",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "traceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "traceLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "traces", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "agent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTrace", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "traceCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "traceLog", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "traces", data: BytesLike): Result;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [oldAgent: AddressLike, newAgent: AddressLike];
  export type OutputTuple = [oldAgent: string, newAgent: string];
  export interface OutputObject {
    oldAgent: string;
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReasonStoredEvent {
  export type InputTuple = [
    recorder: AddressLike,
    traceHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recorder: string,
    traceHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recorder: string;
    traceHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttributionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttributionRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttributionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agent: TypedContractMethod<[], [string], "view">;

  getTrace: TypedContractMethod<
    [traceHash: BytesLike],
    [AttributionRegistry.TraceEntryStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  storeReason: TypedContractMethod<
    [traceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  traceCount: TypedContractMethod<[], [bigint], "view">;

  traceLog: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  traces: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        recorder: string;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTrace"
  ): TypedContractMethod<
    [traceHash: BytesLike],
    [AttributionRegistry.TraceEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeReason"
  ): TypedContractMethod<[traceHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "traceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "traceLog"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "traces"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint] & {
        recorder: string;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReasonStored"
  ): TypedContractEvent<
    ReasonStoredEvent.InputTuple,
    ReasonStoredEvent.OutputTuple,
    ReasonStoredEvent.OutputObject
  >;

  filters: {
    "AgentUpdated(address,address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "ReasonStored(address,bytes32,uint256)": TypedContractEvent<
      ReasonStoredEvent.InputTuple,
      ReasonStoredEvent.OutputTuple,
      ReasonStoredEvent.OutputObject
    >;
    ReasonStored: TypedContractEvent<
      ReasonStoredEvent.InputTuple,
      ReasonStoredEvent.OutputTuple,
      ReasonStoredEvent.OutputObject
    >;
  };
}
